# Generated by Django 3.2.5 on 2021-12-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsDetails',
            fields=[
                ('assetName', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('assetTicker', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('uPortName', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=64)),
                ('assetQuantity', models.FloatField()),
                ('usdSpent', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='AssetPriceMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_close', models.FloatField()),
                ('date', models.DateTimeField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assetsdetails')),
            ],
        ),
    ]
