# Generated by Django 3.2.5 on 2021-12-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='user',
            new_name='port',
        ),
    ]
