# Generated by Django 3.2.5 on 2021-12-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_user_assets_port'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetpricemovements',
            unique_together={('ticker', 'adj_close')},
        ),
    ]
