# Generated by Django 3.2.5 on 2021-12-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_assetpricemovements_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetpricemovements',
            unique_together={('ticker', 'date')},
        ),
    ]
