# Generated by Django 3.2.5 on 2021-12-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_assetpricemovements_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assetName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assetsdetails'),
        ),
    ]
