# Generated by Django 3.2.5 on 2021-12-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_assets_assetname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='assetName',
            new_name='asset',
        ),
    ]
