# Generated by Django 3.2.5 on 2021-12-09 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_assets_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='sold_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 10, 22, 47, 249739)),
        ),
    ]
