# Generated by Django 3.2.5 on 2021-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_assets_sold_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='sold_on',
        ),
        migrations.AddField(
            model_name='assets',
            name='buy_sell_order',
            field=models.BooleanField(default=True),
        ),
    ]
