# Generated by Django 3.2.5 on 2021-12-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20211209_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetQuantity', models.FloatField()),
                ('usdSpent', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assets',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='assetQuantity',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='buy_sell_order',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='port',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='usdSpent',
        ),
        migrations.AddField(
            model_name='assets',
            name='assetName',
            field=models.CharField(default='vd', max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='assetTicker',
            field=models.CharField(default='dv', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetpricemovements',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assets'),
        ),
        migrations.DeleteModel(
            name='AssetsDetails',
        ),
        migrations.AddField(
            model_name='assetspurchase',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assets'),
        ),
        migrations.AddField(
            model_name='assetspurchase',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='assetsold',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assetspurchase'),
        ),
    ]
