# Generated by Django 3.2.5 on 2021-12-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20211210_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default=False)),
                ('assetQuantity', models.FloatField()),
                ('usdSpent', models.FloatField()),
                ('bought_on', models.DateTimeField(auto_now_add=True)),
                ('sold_on', models.DateTimeField(null=True)),
                ('sold_for_usd', models.FloatField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assets')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.RemoveField(
            model_name='assetspurchase',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetspurchase',
            name='port',
        ),
        migrations.DeleteModel(
            name='AssetSold',
        ),
        migrations.DeleteModel(
            name='AssetsPurchase',
        ),
    ]
