# Generated by Django 3.2.5 on 2021-12-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20211203_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
