# Generated by Django 3.2.5 on 2021-12-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpricemovements',
            name='date',
            field=models.DateField(),
        ),
    ]
