# Generated by Django 3.2.5 on 2022-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_assetpricemovements_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sold_on',
            field=models.DateTimeField(null=True),
        ),
    ]
