# Generated by Django 3.2.5 on 2022-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_portfolio_realized_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioassets',
            name='bought_on',
            field=models.DateTimeField(null=True),
        ),
    ]
