# Generated by Django 3.2.5 on 2022-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20220319_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfolioassets',
            name='bought_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
